default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kaDECA_development
  host: localhost

test:
  <<: *default
  database: kaDECA_test
  host: localhost

production:
  <<: *default
  database: kaDECA_production
  username: kaDECA
  password: <%= ENV['KADECA_DATABASE_PASSWORD'] %>
